### ISSUE TITLE
Replace "yoursmilesstring" with a valid SMILES string

### ISSUE THREAD

**Issue by jonlandrum** [ikmckenz/target-pred-py#22]
**Synopsis**
The example SMILE string in the file `README.md` on line 45 is not a valid SMILE string, and results in an error when running the program. A better approach would be to have a valid SMILE string of a common drug to use as an example.

**Acceptance Criteria**
* Find a drug that is not in the training set and which the model can accurately predict; [PubChem](https://pubchem.ncbi.nlm.nih.gov/) is a good resource for this
* Replace the invalid SMILE string in the file `README.md` on line 45 with the SMILE string of the chosen drug

**Comment by saltshaiker** [comment]
@ikmckenz Can I pick this up please?

**Comment by ikmckenz** [comment]
It's yours @d3fau7t
