### ISSUE TITLE
No data?

### ISSUE THREAD

**Issue by watermountain222** [ikmckenz/target-pred-py#35]
Hello, 
I'm just studying as a beginner. 
Until now I don't completely understand your code.
No data-file in the Data folder.
Could you explain where is the data file? 
Or, How do I get the data?

**Comment by ikmckenz** [comment]
Hi! If you work through the Getting Started section of the Reeadme, the part where you run `make_dataset.py` should populate the data directory (if everything still works).

**Comment by watermountain222** [comment]
Thank you, I'll try it :)
